name: Deployment Two
on: push
jobs:
  Deploy:
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Buid Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."